// Generated by Supabase CLI: supabase gen types typescript --project-id <id>
// Run this command after setting up the Supabase project to replace this file.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string | null;
          is_pro: boolean;
          pro_purchased_at: string | null;
          stripe_customer_id: string | null;
          stripe_payment_intent_id: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          email?: string | null;
          is_pro?: boolean;
          pro_purchased_at?: string | null;
          stripe_customer_id?: string | null;
          stripe_payment_intent_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string | null;
          is_pro?: boolean;
          pro_purchased_at?: string | null;
          stripe_customer_id?: string | null;
          stripe_payment_intent_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      dynamic_qrs: {
        Row: {
          id: string;
          user_id: string;
          shortcode: string;
          destination_url: string;
          name: string | null;
          folder_id: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          shortcode: string;
          destination_url: string;
          name?: string | null;
          folder_id?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          shortcode?: string;
          destination_url?: string;
          name?: string | null;
          folder_id?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      folders: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      scans: {
        Row: {
          id: string;
          qr_id: string;
          scanned_at: string;
          country: string | null;
          device_type: string | null;
          browser: string | null;
        };
        Insert: {
          id?: string;
          qr_id: string;
          scanned_at?: string;
          country?: string | null;
          device_type?: string | null;
          browser?: string | null;
        };
        Update: {
          id?: string;
          qr_id?: string;
          scanned_at?: string;
          country?: string | null;
          device_type?: string | null;
          browser?: string | null;
        };
        Relationships: [];
      };
      brand_templates: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          config: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          config: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          config?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: { [_ in never]: never };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};
